# Generated by Django 5.1.1 on 2025-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('iphone', 'iPhone'), ('macbook', 'MacBook'), ('ipad', 'iPad'), ('watch', 'Watch'), ('audio', 'Tai nghe, loa'), ('accessory', 'Phụ kiện'), ('featured', 'Sản phẩm nổi bật')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
