# Generated by Django 5.1.1 on 2025-06-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_featured_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('iphone', 'iPhone'), ('macbook', 'MacBook'), ('ipad', 'iPad'), ('watch', 'Watch'), ('audio', 'Tai nghe, loa'), ('accessory', 'Phụ kiện')], max_length=20),
        ),
    ]
