# Generated by Django 5.2.2 on 2025-06-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productvariant_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='ram',
        ),
    ]
