# Generated by Django 5.2.2 on 2025-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productcolor_productvariant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='storage',
            field=models.CharField(max_length=200),
        ),
    ]
