# Generated by Django 5.2.2 on 2025-07-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_productvariant_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.IntegerField(),
        ),
    ]
