# Generated by Django 4.2.23 on 2025-08-13 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('discount_type', models.CharField(choices=[('percent', 'Giảm theo %'), ('amount', 'Giảm theo số tiền')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
            },
        ),
    ]
