# Generated by Django 4.2.23 on 2025-08-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='end_date',
            field=models.DateTimeField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='start_date',
            field=models.DateTimeField(verbose_name='Ngày bắt đầu'),
        ),
    ]
