# Generated by Django 4.2.23 on 2025-08-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_discountcode_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
