# Generated by Django 4.2.23 on 2025-09-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(help_text='Phần trăm giảm giá (0-100)'),
        ),
    ]
