# Generated by Django 4.2.23 on 2025-09-13 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_order_coupon_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_from',
            field=models.DateTimeField(blank=True, help_text='Bắt đầu (tùy chọn)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Giảm giá (%) cho toàn bộ biến thể khi bật Flash Sale', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_to',
            field=models.DateTimeField(blank=True, help_text='Kết thúc (tùy chọn)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False, help_text='Bật tắt Flash Sale'),
        ),
    ]
